### ISSUE TITLE
ResampleLayer cannot do backward.

### ISSUE THREAD

**Issue by lhoangan** [JingchunCheng/SegFlow#10]
Hi, I was trying to train with the given script, while the error popped up:

Number of Objects: 1
Class 0, weight = 0.0862924456596
Class 1, weight = 0.91370755434
F0321 17:42:25.721662 26384 resample_layer.cu:211] ResampleLayer cannot do backward.

Could you have a look at them, I'm not sure how to fix that.

**Comment by JingchunCheng** [comment]
The resample layer in SegFlow is used as part of the input layer.
It does not need to do backward.

**Comment by lhoangan** [comment]
There are 3 Resample Layers being used in the [train_SegFlow_DAVIS2016_PN.prototxt](https://github.com/JingchunCheng/SegFlow/blob/master/training/train_SegFlow_DAVIS2016_PN.prototxt):
one at line 4583, one at line 4595, and one at 5407. I guess the first twos are to do with the input, so the last might cause the trouble.

```
layer {
  name: "Resample4"
  type: "Resample"
  bottom: "blob44"
  top: "predict_flow_resize"
  resample_param {
    width: 854
    height: 480
    type: LINEAR
    antialias: true
  }
}
```

**Comment by JingchunCheng** [comment]
Actually, we did not use the output of this layer.
The flow prediction is from the concatenated features of segmentation and flow branch.

**Comment by lhoangan** [comment]
I've removed third Resample Layer, and add propagate_down:false to the first twos, but still I've got the same error.

**Comment by JingchunCheng** [comment]
You need to delete that sentence " LOG(FATAL) << "ResampleLayer cannot do backward." in resample_layer.cu and resample_layer.cpp.

**Comment by lhoangan** [comment]
It's working now, thank you for your prompt support.
