### ISSUE TITLE
docker version

### ISSUE THREAD

**Issue by jakeoung** [JingchunCheng/SegFlow#3]
I have difficulty installing on my desktop. Also, if I run the demo based on caffe docker version, it has error something like:

Message type "caffe.LayerParameter" has no field named "augmentation_param"

My question is that is there any docker version that I can run?

**Comment by wasidennis** [comment]
Currently we do not have the docker version and will work on it.

The error you got is because the caffe image you use does not contain "augmentation_param". You would need to install the caffe contained in our repository or from the FlowNet: https://github.com/liruoteng/FlowNet.

**Comment by jakeoung** [comment]
It helps me. I used the docker of FlowNet and finally can run your program. Thanks!

**Comment by wasidennis** [comment]
Thanks for your updates!
