### ISSUE TITLE
caffe.LayerParameter has no field named "augmentation_param"

### ISSUE THREAD

**Issue by nikepakou** [JingchunCheng/SegFlow#4]
Hi, Jingchun, when i run python infer_DAVIS.py dog, occured some error :
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 4578:22: Message type "caffe.LayerParameter" has no field named "augmentation_param".
F0925 20:41:47.197806  1821 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ../model/deploy.prototxt 
Can you help me to slove this problem?

**Comment by wasidennis** [comment]
Have you installed the caffe contained in this repository? If yes, you should also include its pycaffe path (repository_path/caffe/python) in $PYTHONPATH. If you do both and still cannot install our caffe successfully, you may try to install the docker version of FlowNet that contains all required dependencies.

**Comment by nikepakou** [comment]
@wasidennis  Thanks , I solved it . I installed caffe downloaded from [https://github.com/BVLC/caffe ](url), Are there some differents between caffe contained in this repository and BVLC/caffe ?
