### ISSUE TITLE
finetuning the segmentation network (online training)

### ISSUE THREAD

**Issue by jakeoung** [JingchunCheng/SegFlow#6]
At the end of Section 4.1 in the paper, there is a description of online training for segmentation.

I want to finetune the segmentation. Can I know how to do it? Or, if I test

`python infer_DAVIS.py VIDEO_NAME`,

is it automatically finetuned, using the segmentation in the first frame?

**Comment by wasidennis** [comment]
Hi @jakeoung,

The code in this repository does not contain the finetuning part. If you want to finetune the model on a specific object, please take a look at our another repository for the example: https://github.com/JingchunCheng/Seg-with-SPN. They have different models but the methodology for finetuning is the same.
